if GGF.locale == nil then GGF.locale = {} end

-- Player Status
GGF.locale['Dead']                      = "Tot"
GGF.locale['Offline']                   = "Offline"
 
GGF.locale['Frame_Lock']                = "Alle Elemente sperren (/ggf)"
 
-- Display:
GGF.locale["Display_Player_Info"]       = "Zeige Charakterinformationen"
GGF.locale["Display_Player_Experience"] = "Zeige Leiste für Erfahrungspunkte"
 
-- Global
GGF.locale['Combat_Alpha']              = "Transparenz außerhalb des Kampfes"
GGF.locale['Font']      = "Schrift"
GGF.locale['Font_Style']    = "Schriftart"
GGF.locale['Bar_Texture']               = "Textur"
GGF.locale["Bar_Format"]                = "Stil der Leistenbeschriftung"
GGF.locale["Bar_Format_Location"]       = "Position der Leistenbeschriftung"
GGF.locale["Bar_Format_Two"]            = "Zweite Leistenbeschriftungart"
GGF.locale["Bar_Format_Location_Two"]   = "Zweite Leistenbeschriftungsposition"
 
-- Frame Options
GGF.locale["Frame_PositionX"]     = "Horizontale Fensterposition"
GGF.locale["Frame_PositionY"]           = "Vertikale Fensterposition"
GGF.locale['Frame_Width']               = "Fensterbreite"
GGF.locale['Frame_Height']              = "Fensterhöhe"
GGF.locale['Info_FontSize']   = "Charakterinfo Schriftart"
GGF.locale['Info_FontColor']    = "Charakterinfo Schriftfarbe"
GGF.locale['Player_Padding']            = "Abstand zwischen den Leisten"
GGF.locale['Health_Height']             = "Höhe der Gesundheitsleiste"
GGF.locale['Health_BarColor']           = "Farbe der Gesundheitsleiste"
GGF.locale['Health_FontSize']           = "Schriftgröße der Gesundheitsleiste"
GGF.locale['Health_FontColor']          = "Schriftfarbe der Gesundheitsleiste"
GGF.locale["Magicka_Height"]            = "Höhe der Magickaleiste"
GGF.locale["Magicka_BarColor"]          = "Farbe der Magickaleiste"
GGF.locale["Magicka_FontSize"]          = "Schriftgröße der Magickaleiste"
GGF.locale["Magicka_FontColor"]         = "Schriftfarbe der Magickaleiste"
GGF.locale["Stamina_Height"]            = "Höhe der Ausdauerleiste"
GGF.locale["Stamina_BarColor"]          = "Farbe der Ausdauerleiste"
GGF.locale["Stamina_FontSize"]          = "Schriftgröße der Ausdauerleiste"
GGF.locale["Stamina_FontColor"]         = "Schriftfarber der Ausdauerleiste"
GGF.locale["Experience_Height"]   = "Höhe der Erfahrungsleiste"
GGF.locale["Experience_BarColor"] = "Farbe der Erfahrungsleiste"
GGF.locale["Experience_Text_Display"] = "Text der Erfahrungsleiste zeigen"
GGF.locale["Experience_FontSize"] = "Schriftgröße der Erfahrungsleiste"
GGF.locale["Experience_FontColor"]  = "Schriftfarbe der Erfahrungsleiste"
GGF.locale["Mount_Height"]              = "Höhe der Reittierleiste"
GGF.locale["Mount_BarColor"]            = "Farbe der Reittierleiste"
GGF.locale["Target_FontColor_Friendly"] = "Schriftfarbe für Verbündete"
GGF.locale["Target_FontColor_Hostile"]  = "Schriftfarbe für Feinde"
GGF.locale["Target_FontColor_Interact"] = "Schriftfarbe für neutrale Ziele"
 
-- Misc Setting
GGF.locale['Setting_Global']            = "Accountweite Addon Einstellungen"
GGF.locale['Setting_Player']            = "Charakter"
GGF.locale['Setting_Player_Health']     = "Charakter: Gesundheit"
GGF.locale['Setting_Player_Magicka']    = "Charakter: Magicka"
GGF.locale['Setting_Player_Stamina']    = "Charakter: Ausdauer"
GGF.locale['Setting_Player_Experience'] = "Charakter: Erfahrungspunkte"
GGF.locale['Setting_Player_Mount']      = "Charakter: Reittier"
GGF.locale['Setting_Group']             = "Gruppenfenster"
GGF.locale['Setting_Raid']              = "Schlachtzugsfenster"
GGF.locale['Setting_Raid_Layout']       = "Layout für Schlachtzugsgruppen"
GGF.locale['Setting_Target']            = "Ziel"
GGF.locale['Setting_Defaults']          = "Einstellung zurücksetzen"
GGF.locale['Setting_Reset_Warning']     = "Achtung! Alle Einstellungen werden auf die Standardeinstellungen zurückgesetzt. Wenn du dir sicher bist, klicke unten auf die Schaltfläche."
GGF.locale['Setting_Reset_Button']      = "Alle Einstellungen zurücksetzen"